# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "#{ENV['VAGRANT_BOX']}"
	config.vm.box_check_update = false

	config.ssh.forward_agent = true

	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", 512]
		vb.customize ["modifyvm", :id, "--cpus", 1]

		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	# setup Python 2.7 for Ansible
	config.vm.provision "shell" do |shell|
		shell.inline = "apt-get update "\
			"&& apt-get install python2.7 -y "\
			"&& ln -fs /usr/bin/python2.7 /usr/bin/python"
	end

	# Test "build" tag
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "test.yml"
		ansible.tags = [ "build" ]
		ansible.verbose = "#{ENV['VERBOSE']}" if ENV['VERBOSE']
	end

	# Test "configure" tag
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "test.yml"
		ansible.tags = [ "configure" ]
		ansible.verbose = "#{ENV['VERBOSE']}" if ENV['VERBOSE']
	end

	# Run assertions
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "test.yml"
		ansible.tags = [ "assert" ]
		ansible.verbose = "#{ENV['VERBOSE']}" if ENV['VERBOSE']
	end
end
